### PR TITLE
simplify building on unix systems

### PR DESCRIPTION
**Pull request by john-tornblom**
Invoking functions on the ps5 works fine, but what is returned from API.call(...)? Invoking "getpid" returns a valid pointer, but what is it pointing at?

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
It should return the value not pointer.

**Comment by john-tornblom** [comment]
Alright, I will investigate further, thanks.

**Comment by john-tornblom** [comment]
I have been investigating further (see https://github.com/john-tornblom/bdj-sdk/tree/master/samples/ps5-invoke-native).
It seems the return value from the gadget is not what I expedited it to be. For example, when I invoke getpid", I get a very large number back.

**Comment by TheOfficialFloW** [comment]
Well, then just use the API from my repo? Why do you reimplement it and then complain here?

**Comment by john-tornblom** [comment]
You are right, I'll try to reproducer my problem from your code base instead...

**Pull request merged**
